version: "3.1"

services:
  server:
    image: bluerain/policr
    stdin_open: true
    ports:
      - 8083:8080
    environment:
      POLICR_BOT_TOKEN: <Your_Bot_Token>
      POLICR_BOT_USERNAME: <Your_Bot_Username>
      POLICR_BOT_SNAPSHOT_CHANNEL: <Your_Snapshot_Channel>
      POLICR_BOT_VOTING_CHANNEL: <Your_Voting_Channel>
    restart: always
